#########################################################################
#This file provides the configurations for the pipeline to run.
#########################################################################

#Add below the paths to the ...

#runfolder if demultiplexing and bcl to fastq conversion is desired
runfolder: /data/users/nkueng/220818_A00574_0806_AHFYNMDRX2
out_fastq: /data/users/nkueng/trial_fastq

#fastq file
fastqdir: /data/users/nkueng/Twist_FASTQ/FASTQ

#results directory
resultsdir: /data/users/nkueng/twist_hyb1_output_SNP_masked

#temporary folder directory
tmp-dir: $SCRATCH

#########################################################################
#locations
#########################################################################
#adapter_sequences:

#files required for panel specific metrics collection
targetregions_all: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info/submission_full_final.bed
targetregions_meth: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info/submission3_methyl_final.bed
targetregions_snp: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info/submission3_SNPs_final.bed

bait_regions_all: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info/Probes_merged_ok_combined_Methyl_Inselspital_targetedTOOpanel_MTE-94463566_hg19.bed
bait_regions_meth: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info/probes_MTE-94463566_meth.bed
bait_regions_snp: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info/probes_MTE-94463566_snp.bed

interval_list_out_dir: /data/users/nkueng/Project_folders/twist_panel/1.5x_tiling_MTE-94463566_hg19/panel_info

#reference genome
genome_version: hg19_cerebis        #add the name of the genome version (hg19, hg38)
#reference_w_ctrl: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/hg19_cerebis/hg19_cerebis.fa
#reference_wo_ctrl: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/hg19/hg19.fa
#reference_ctrl: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/CEREBIS/cerebis_ref.fa

reference_w_ctrl: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/hg19_cerebis/hg19_cerebis_masked/hg19_cerebis_sub3_masked.fa
reference_wo_ctrl: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/hg19/masked_hg19/hg19_sub3_masked.fa
reference_ctrl: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/CEREBIS/cerebis_ref.fa
sequence_dictionary_output_dir: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/hg19_cerebis/hg19_cerebis_masked

#sequence_dictionary_output_dir: /data/users/nkueng/cfDNApipe/reference_cfDNApipe/hg19_cerebis
biscuit_assets_hg19_dir: /data/users/nkueng/references/biscuit_assets/hg19
biscuit_assets_cerebis_dir: /data/users/nkueng/references/biscuit_assets/cerebis

#########################################################################
#paramters.
##########################################################################
reads_per_umi: 1
umi_tools_grouping_method: directional #method for UMI grouping, directional is default (https://umi-tools.readthedocs.io/en/latest/reference/dedup.html)
remove_dup_picard: true #remove duplicates with MarkDuplicates from picard, options: true or false