#########################################################################
# This file provides the configurations for the pipeline to run.
#########################################################################

# Add below the paths to the ...
# fastq file
fastqdir: /path/to/fastq_dir

# results directory, this directory will be created, please specify the name of this directory where all results will be stored
resultsdir: /path/to/results_dir

# temporary folder directory
tmp-dir: /path/to/tmp

# path to config file for the multiqc module.
multiqc_config: "../config/muliqc_config.yaml" # Do not change !!


#########################################################################
# Reference and Target regions Directories
#########################################################################

# files required for panel specific metrics collection
targetregions_all: </path/to/>TransMethylCFDx/resources/markers3_1_full_final.bed
targetregions_meth: </path/to/>TransMethylCFDx/resources/markers3_1_methyl_final.bed
targetregions_snp: </path/to/>TransMethylCFDx/resources/markers3_1_SNPs_final.bed

bait_regions_all: </path/to/>TransMethylCFDx/resources/Probes_merged_ok_combined_Methyl_Inselspital_targetedTOOpanel_MTE-91197412_hg19.bed
bait_regions_meth: </path/to/>TransMethylCFDx/resources/probes_MTE-91197412_meth.bed
bait_regions_snp: </path/to/>TransMethylCFDx/resources/probes_MTE-91197412_snp.bed

interval_list_out_dir: </path/to/>TransMethylCFDx/resources/

# reference genome (with index file in same directory)
# since the workflow assumes that the CEREBIS sequence is added to the samples, it includes this sequence in the reference_w_ctrl. If your samples do not include the CEREBIS sequence, stil use the reference_w_ctrl, otherwise the workflow will fail.
# just create a hg19 reference including the CEREBIS sequence and one without the CEREBIS sequence and provide the paths here.
genome_version: hg19        #add the name of the genome version (hg19, hg38, etc.)
reference_w_ctrl: </path/to/referenceWithControlSequences>
reference_wo_ctrl: </path/to/referenceWithOutControlSequences>

# add here the reference files (with index file in same directory)
# these are the control sequences (unmethylated, fully methylated etc. which are in the reference_w_ctrl). However, if your samples do not include these control sequences, you can ignore these references.
reference_cerebis: </path/to/cerebis_reference>
#reference_lambda: /path/to/unmethylatedLambda
#reference_pUC19: /path/to/methylatedpUC19
sequence_dictionary_output_dir: /path/to/ #the output dir of the generated .dict files

# these are used for the BISUIT module (more info see https://huishenlab.github.io/biscuit/docs/faq.html)
biscuit_assets_dir: /data/users/nkueng/references/biscuit_assets/hg19
biscuit_assets_cerebis_dir: /data/users/nkueng/references/biscuit_assets/cerebis
#biscuit_assets_lambda_dir: /data/users/nkueng/references/biscuit_assets/lambda
#biscuit_assets_pUC19_dir: /data/users/nkueng/references/biscuit_assets/pUC19

#########################################################################
# paramters
##########################################################################
reads_per_umi: 1  # reads per umi for consensus read creation
umi_tools_grouping_method: directional # method for UMI grouping, directional is default (https://umi-tools.readthedocs.io/en/latest/reference/dedup.html)
remove_dup_picard: true # remove duplicates with MarkDuplicates from picard, options: true or false